name: XJ CICD Workshop Workflow
on:  
  push:
  release: 
jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
      #https://github.com/marketplace/actions/build-and-push-docker-images 
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true    
          tags: moksha51/randnum:${{ github.ref_name }} #need to change this to take current tag 

      #https://github.com/marketplace/actions/slack-send
      -
        name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          channel-id: '#sa54-test-submission'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: ${{ env.Name }}\nMatriculation: ${{ env.M_Num }}\nEmail: ${{ env.Email }}\nRepo: ${{ env.REPOSITORY }}\nImage name: ${{ env.Image_Name }}\nImage url: ${{ env.Image_URL }}"
                  }
                }
              ]
            }
        env:
          Image_Name: ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.ref_name }} 
          Image_URL: ${{ secrets.DOCKER_IMAGE_URL }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          Name: TAN XINGJIE
          M_Num: A0249465R
          Email: e0941658@u.nus.edu
          REPOSITORY: git://github.com:moksha51/randnum.git
